
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh
 */
public class SeatPanel extends javax.swing.JPanel {
    GridBagLayout layout=new GridBagLayout();
    PVRPanel pvr;
    CinemaxPanel cp;
      TheaterPanel tp=new TheaterPanel();

    /**
     * Creates new form SeatPanel
     */
    public SeatPanel() {
        initComponents();
       
         pvr=new PVRPanel();
         cp=new CinemaxPanel();
         SeatPanel.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
       
         
      
         
       
        
      
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeatPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(831, 400));

        SeatPanel.setBackground(new java.awt.Color(44, 62, 80));
        SeatPanel.setPreferredSize(new java.awt.Dimension(831, 400));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Please Submit The Theater Form");

        javax.swing.GroupLayout SeatPanelLayout = new javax.swing.GroupLayout(SeatPanel);
        SeatPanel.setLayout(SeatPanelLayout);
        SeatPanelLayout.setHorizontalGroup(
            SeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeatPanelLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(283, 283, 283))
        );
        SeatPanelLayout.setVerticalGroup(
            SeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SeatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SeatPanel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SeatPanel;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
