
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh
 */
public class TheaterPanel extends javax.swing.JPanel {

    /**
     * Creates new form TheaterPanel
     */
    public TheaterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToggleButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Dynamicpanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxTiming = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSelectedTime = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jRadioButtonPVR = new javax.swing.JRadioButton();
        jRadioButtonCinemax = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(831, 400));

        Dynamicpanel1.setBackground(new java.awt.Color(44, 62, 80));
        Dynamicpanel1.setPreferredSize(new java.awt.Dimension(831, 400));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Select Timings :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Select Theater :");

        ComboBoxTiming.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBoxTiming.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 AM", "10:00 AM", "12:15 AM", "02:00 AM", "03:30 PM", "06:45 PM", "07:45 PM", "10:00 PM", "11:00 PM" }));
        ComboBoxTiming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTimingActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Selected Time :");

        txtSelectedTime.setEditable(false);
        txtSelectedTime.setBackground(new java.awt.Color(108, 122, 137));
        txtSelectedTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSelectedTime.setForeground(new java.awt.Color(228, 241, 254));

        btnSubmit.setBackground(new java.awt.Color(242, 38, 19));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jRadioButtonPVR.setBackground(new java.awt.Color(255, 255, 255));
        ToggleButtonGroup.add(jRadioButtonPVR);
        jRadioButtonPVR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonPVR.setText("PVR");
        jRadioButtonPVR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPVRActionPerformed(evt);
            }
        });

        jRadioButtonCinemax.setBackground(new java.awt.Color(255, 255, 255));
        ToggleButtonGroup.add(jRadioButtonCinemax);
        jRadioButtonCinemax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonCinemax.setText("CINEMAX");

        javax.swing.GroupLayout Dynamicpanel1Layout = new javax.swing.GroupLayout(Dynamicpanel1);
        Dynamicpanel1.setLayout(Dynamicpanel1Layout);
        Dynamicpanel1Layout.setHorizontalGroup(
            Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dynamicpanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dynamicpanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jRadioButtonPVR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonCinemax)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dynamicpanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dynamicpanel1Layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dynamicpanel1Layout.createSequentialGroup()
                        .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSelectedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxTiming, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176))))
        );
        Dynamicpanel1Layout.setVerticalGroup(
            Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dynamicpanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPVR)
                    .addComponent(jRadioButtonCinemax))
                .addGap(56, 56, 56)
                .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTiming, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(Dynamicpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelectedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dynamicpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dynamicpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTimingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTimingActionPerformed
        // TODO add your handling code here:
        txtSelectedTime.setText(ComboBoxTiming.getSelectedItem().toString());
    }//GEN-LAST:event_ComboBoxTimingActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Submitted Successfully Now Press Select Seat");
      
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jRadioButtonPVRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPVRActionPerformed
    
        
    }//GEN-LAST:event_jRadioButtonPVRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTiming;
    private javax.swing.JPanel Dynamicpanel1;
    private javax.swing.ButtonGroup ToggleButtonGroup;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JRadioButton jRadioButtonCinemax;
    public javax.swing.JRadioButton jRadioButtonPVR;
    private javax.swing.JTextField txtSelectedTime;
    // End of variables declaration//GEN-END:variables
}
